### ISSUE TITLE
Update Kabanero CR instance configuration for Stacks / Versions

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/docs#272]
Both the conversion from collections to stacks, and the multi-version stack support, make updates necessary to https://kabanero.io/docs/ref/general/configuration/kabanero-cr-config.html.

We need to wholesale compare the Kabanero CRD to what's here, and make necessary changes.  Similarly, the Collection is replaced with Stack, so the Stack CRD should be compared against what is here now for Collection and updates should be made.

**Comment by davco01a** [comment]
We need to cover default and nested pipelines too:

```
stacks:
    pipelines:
    - https:
        skipCertVerification: false
        url: https://github.com/kabanero-io/collections/releases/download/0.5.0-rc.4/incubator.common.pipeline.default.tar.gz
      id: default
      sha256: 6537a5a25f845266d6b81c47d97a97c711a98306a78339d039d5af8ed700bff5
    repositories:
      - https:
          skipCertVerification: false
          url: >-
            https://github.com/kabanero-io/collections/releases/download/0.5.0/kabanero-index.yaml
        name: central
      - https:
          skipCertVerification: false
          url: >-
            https://github.com/kabanero-io/collections/releases/download/0.3.5/kabanero-index.yaml
        name: central2
```
