### ISSUE TITLE
Enhance automation in script to automate appsody kubectl apply(s) and edits

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/docs#30]
Enhance the script to do the following after the initial istio and kabanero pod setup:

1. git clone https://github.com/appsody/tekton-example as part of this one script too
2. cd tekton-example
3. oc project kabanero
4. kubectl apply -f appsody-service-account.yaml
5. kubectl apply -f appsody-cluster-role-binding.yaml
6. automate editing and apply of docker secrets, also have script prompt for docker credentials:
```
apiVersion: v1
kind: Secret
metadata:
  name: my-docker-secret
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v1/ 
type: kubernetes.io/basic-auth
stringData:
  username: <your docker userid>
  password: <your docker password>
```
```
kubectl apply -f my-docker-secret.yaml
```
7. kubectl edit serviceaccount appsody-sa
add:
```
secrets:
- name: my-docker-secret
```
8. kubectl apply -f appsody-build-task.yaml
9. kubectl apply -f appsody-build-pipeline.yaml
10.  Write to appsody-pipeline-resources.yaml (prompt for docker id and github id):
```
params:
  - name: url
    value: index.docker.io/your-userid/my-appsody-image
    type: image
```
```
spec:
  params:
  - name: revision
    value: master
  - name: url
    value: https://github.com/your-userid/appsody-test-project
```
```
kubectl apply -f appsody-pipeline-resources.yaml
```
11. kubectl apply -f appsody-pipeline-run.yaml
